// Saudi districts data organized by city
export const SAUDI_DISTRICTS: { [city: string]: string[] } = {
  Riyadh: [
    "Al Olaya",
    "Al Malaz",
    "Al Naseem",
    "Al Rawdah",
    "Al Sulaimaniyah",
    "Al Nakheel",
    "Al Sahafah",
    "Al Falah",
    "Al Murabba",
    "Al Batha",
    "Al Dirah",
    "Al Masif",
    "Al Mansourah",
    "Al Yarmouk",
    "Al Rehab",
    "Al Narjis",
    "Al Aqiq",
    "Al Hamra",
    "Al Wurud",
    "Al Sabeq",
    "Al Nada",
    "Al Rihab",
  ],
  Jeddah: [
    "Al Balad",
    "Al Hamra",
    "Al Zahra",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Rawdah",
    "Al Safa",
    "Al Salamah",
  ],
  Abha: [
    "Al Andalus",
    "Al Faisaliyah",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  "Khamis Mushait": [
    "Al Andalus",
    "Al Faisaliyah",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Dammam: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Dhahran: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Khobar: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  "Ras Tanura": [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Safwa: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Anak: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Qatif: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Saihat: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Tarut: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Hofuf: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  AlMubarraz: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Hassa: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Jubail: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Jizan: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  "Abu Arish": [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Sabya: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Madinah: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Makkah: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
  Tabuk: [
    "Al Faisaliyah",
    "Al Andalus",
    "Al Zahra",
    "Al Rawdah",
    "Al Sabeel",
    "Al Rehab",
    "Al Naeem",
    "Al Safa",
    "Al Salamah",
  ],
};

// Helper function to get districts for a specific city
export function getDistrictsForCity(city: string): string[] {
  return SAUDI_DISTRICTS[city] || [];
}
